name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-11.0

    steps:
    - uses: actions/checkout@v2
      
    - name: Switch to latest Xcode
      uses: maxim-lobanov/setup-xcode@v1.2.1
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
